# NOTE: Generated By HttpRunner v3.1.4
# FROM: har\mubu.har


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCaseMubu(HttpRunner):

    config = Config("testcase description").verify(False)

    teststeps = [
        Step(
            RunRequest("/")
            .get("https://mubu.com/")
            .with_headers(
                **{
                    "user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:86.0) Gecko/20100101 Firefox/86.0",
                    "accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8",
                    "accept-language": "zh-CN,zh;q=0.8,zh-TW;q=0.7,zh-HK;q=0.5,en-US;q=0.3,en;q=0.2",
                    "accept-encoding": "gzip, deflate, br",
                    "upgrade-insecure-requests": "1",
                    "te": "trailers",
                }
            )
            .with_cookies(
                **{
                    "Hm_lvt_4426cbb0486a79ea049b4ad52d81b504": "1615345245,1615346444,1615354082,1615359653",
                    "SLARDAR_WEB_ID": "2b405986-4ecb-48ae-aadd-901b590d7fc5",
                    "_ga": "GA1.2.859944035.1590457736",
                    "mubu_inner": "1",
                    "use-redesign": "1",
                    "data_unique_id": "dc1ace1f-23f8-4634-bf93-07f9980b7fa0",
                    "language": "en-US",
                    "country": "US",
                    "_gid": "GA1.2.390527052.1615345025",
                    "reg_entrance": "https%3A%2F%2Fmubu.com%2F",
                    "reg_prepareId": "1781af0a033-1781af0a01c-419e-b942-e163055b8574",
                    "reg_focusId": "33958407-cae2-419e-b942-1781af0a512",
                    "reg_from": "https%3A%2F%2Fwww.baidu.com%2Flink%3Furl%3D7f5FbBhF-mRs1HPXrBCVKU_OweU60QlxumgnADAIgTO%26wd%3D%26eqid%3D86df049c0013d4af000000046048365a",
                    "csrf_token": "452a6317-b763-4356-a2ff-8875df178fbb",
                    "SESSION": "c72693b4-e875-4325-a121-eedfef6c560a",
                    "Hm_lpvt_4426cbb0486a79ea049b4ad52d81b504": "1615359682",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
        ),
        Step(
            RunRequest("/v3/api/document/version/list")
            .post("https://api2.mubu.com/v3/api/document/version/list")
            .with_headers(
                **{
                    "content-length": "0",
                    "jwt-token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiNTYzNDEyMyIsImxvZ2luVHlwZSI6IndlaXhpbiIsImlhdCI6MTYxNDY0Nzc1NH0.tdY4nhpdfF6QYXRCZNYvai9jnOZ17s405MOUpmdSFeI5Snywn6gkfOseHhA5Zmw8FiGDlrhCCWPsoOmSxDg-kQ",
                    "mubu-desktop": "true",
                    "platform": "win32",
                    "platform-version": "10.0.18363",
                    "token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiNTYzNDEyMyIsImxvZ2luVHlwZSI6IndlaXhpbiIsImlhdCI6MTYxNDY0Nzc1NH0.tdY4nhpdfF6QYXRCZNYvai9jnOZ17s405MOUpmdSFeI5Snywn6gkfOseHhA5Zmw8FiGDlrhCCWPsoOmSxDg-kQ",
                    "user-agent": "windows Mubu Electron",
                    "userid": "5634123",
                    "version": "3.0.2",
                    "sec-fetch-site": "none",
                    "sec-fetch-mode": "no-cors",
                    "sec-fetch-dest": "empty",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN",
                }
            )
            .with_data("")
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/login")
            .get("https://mubu.com/login")
            .with_headers(
                **{
                    "user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:86.0) Gecko/20100101 Firefox/86.0",
                    "accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8",
                    "accept-language": "zh-CN,zh;q=0.8,zh-TW;q=0.7,zh-HK;q=0.5,en-US;q=0.3,en;q=0.2",
                    "accept-encoding": "gzip, deflate, br",
                    "referer": "https://mubu.com/",
                    "upgrade-insecure-requests": "1",
                    "te": "trailers",
                }
            )
            .with_cookies(
                **{
                    "Hm_lvt_4426cbb0486a79ea049b4ad52d81b504": "1615345245,1615346444,1615354082,1615359653",
                    "SLARDAR_WEB_ID": "6ac294f5-e0ce-4d4e-bee2-d8c0e302dc0c",
                    "_ga": "GA1.2.859944035.1590457736",
                    "mubu_inner": "1",
                    "use-redesign": "1",
                    "data_unique_id": "dc1ace1f-23f8-4634-bf93-07f9980b7fa0",
                    "language": "en-US",
                    "country": "US",
                    "_gid": "GA1.2.390527052.1615345025",
                    "reg_entrance": "https%3A%2F%2Fmubu.com%2F",
                    "reg_prepareId": "1781af0a033-1781af0a01c-419e-b942-e163055b8574",
                    "reg_focusId": "33958407-cae2-419e-b942-1781af0a512",
                    "reg_from": "https%3A%2F%2Fwww.baidu.com%2Flink%3Furl%3D7f5FbBhF-mRs1HPXrBCVKU_OweU60QlxumgnADAIgTO%26wd%3D%26eqid%3D86df049c0013d4af000000046048365a",
                    "csrf_token": "452a6317-b763-4356-a2ff-8875df178fbb",
                    "SESSION": "c72693b4-e875-4325-a121-eedfef6c560a",
                    "Hm_lpvt_4426cbb0486a79ea049b4ad52d81b504": "1615359769",
                    "_gat": "1",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
        ),
        Step(
            RunRequest("/login/password")
            .get("https://mubu.com/login/password")
            .with_headers(
                **{
                    "user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:86.0) Gecko/20100101 Firefox/86.0",
                    "accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8",
                    "accept-language": "zh-CN,zh;q=0.8,zh-TW;q=0.7,zh-HK;q=0.5,en-US;q=0.3,en;q=0.2",
                    "accept-encoding": "gzip, deflate, br",
                    "referer": "https://mubu.com/login",
                    "upgrade-insecure-requests": "1",
                    "te": "trailers",
                }
            )
            .with_cookies(
                **{
                    "Hm_lvt_4426cbb0486a79ea049b4ad52d81b504": "1615345245,1615346444,1615354082,1615359653",
                    "SLARDAR_WEB_ID": "a2bd086e-9af9-43ba-9318-17ce14e46511",
                    "_ga": "GA1.2.859944035.1590457736",
                    "mubu_inner": "1",
                    "use-redesign": "1",
                    "data_unique_id": "dc1ace1f-23f8-4634-bf93-07f9980b7fa0",
                    "language": "en-US",
                    "country": "US",
                    "_gid": "GA1.2.390527052.1615345025",
                    "reg_entrance": "https%3A%2F%2Fmubu.com%2F",
                    "reg_prepareId": "1781af2032e-1781af20204-4f6d-b299-e0e43bb80be8",
                    "reg_focusId": "ff873384-430e-4f6d-b299-1781af20791",
                    "reg_from": "https%3A%2F%2Fwww.baidu.com%2Flink%3Furl%3D7f5FbBhF-mRs1HPXrBCVKU_OweU60QlxumgnADAIgTO%26wd%3D%26eqid%3D86df049c0013d4af000000046048365a",
                    "csrf_token": "452a6317-b763-4356-a2ff-8875df178fbb",
                    "SESSION": "c72693b4-e875-4325-a121-eedfef6c560a",
                    "Hm_lpvt_4426cbb0486a79ea049b4ad52d81b504": "1615359771",
                    "_gat": "1",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
        ),
        Step(
            RunRequest("/api/login/submit")
            .post("https://mubu.com/api/login/submit")
            .with_headers(
                **{
                    "user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:86.0) Gecko/20100101 Firefox/86.0",
                    "accept": "application/json, text/javascript, */*; q=0.01",
                    "accept-language": "zh-CN,zh;q=0.8,zh-TW;q=0.7,zh-HK;q=0.5,en-US;q=0.3,en;q=0.2",
                    "accept-encoding": "gzip, deflate, br",
                    "content-type": "application/x-www-form-urlencoded; charset=UTF-8",
                    "x-requested-with": "XMLHttpRequest",
                    "content-length": "52",
                    "origin": "https://mubu.com",
                    "referer": "https://mubu.com/login/password",
                    "te": "trailers",
                }
            )
            .with_cookies(
                **{
                    "Hm_lvt_4426cbb0486a79ea049b4ad52d81b504": "1615345245,1615346444,1615354082,1615359653",
                    "SLARDAR_WEB_ID": "ee80671d-23e3-4417-9e02-2cf123ae0ac1",
                    "_ga": "GA1.2.859944035.1590457736",
                    "mubu_inner": "1",
                    "use-redesign": "1",
                    "data_unique_id": "dc1ace1f-23f8-4634-bf93-07f9980b7fa0",
                    "language": "en-US",
                    "country": "US",
                    "_gid": "GA1.2.390527052.1615345025",
                    "reg_entrance": "https%3A%2F%2Fmubu.com%2F",
                    "reg_prepareId": "1781af2032e-1781af20204-4f6d-b299-e0e43bb80be8",
                    "reg_focusId": "ff873384-430e-4f6d-b299-1781af20791",
                    "reg_from": "https%3A%2F%2Fwww.baidu.com%2Flink%3Furl%3D7f5FbBhF-mRs1HPXrBCVKU_OweU60QlxumgnADAIgTO%26wd%3D%26eqid%3D86df049c0013d4af000000046048365a",
                    "csrf_token": "452a6317-b763-4356-a2ff-8875df178fbb",
                    "SESSION": "c72693b4-e875-4325-a121-eedfef6c560a",
                    "Hm_lpvt_4426cbb0486a79ea049b4ad52d81b504": "1615359773",
                    "_gat": "1",
                }
            )
            .with_data(
                {"phone": "18362947918", "password": "gjj19920318", "remember": "true"}
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
            .assert_equal("body.msg", None)
        ),
        Step(
            RunRequest("/app")
            .get("https://mubu.com/app")
            .with_headers(
                **{
                    "user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:86.0) Gecko/20100101 Firefox/86.0",
                    "accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8",
                    "accept-language": "zh-CN,zh;q=0.8,zh-TW;q=0.7,zh-HK;q=0.5,en-US;q=0.3,en;q=0.2",
                    "accept-encoding": "gzip, deflate, br",
                    "referer": "https://mubu.com/login/password",
                    "upgrade-insecure-requests": "1",
                    "te": "trailers",
                }
            )
            .with_cookies(
                **{
                    "Hm_lvt_4426cbb0486a79ea049b4ad52d81b504": "1615345245,1615346444,1615354082,1615359653",
                    "SLARDAR_WEB_ID": "ee80671d-23e3-4417-9e02-2cf123ae0ac1",
                    "_ga": "GA1.2.859944035.1590457736",
                    "mubu_inner": "1",
                    "use-redesign": "1",
                    "data_unique_id": "dc1ace1f-23f8-4634-bf93-07f9980b7fa0",
                    "language": "en-US",
                    "country": "US",
                    "_gid": "GA1.2.390527052.1615345025",
                    "reg_entrance": "https%3A%2F%2Fmubu.com%2F",
                    "reg_prepareId": "1781af2032e-1781af20204-4f6d-b299-e0e43bb80be8",
                    "reg_focusId": "ff873384-430e-4f6d-b299-1781af20791",
                    "reg_from": "https%3A%2F%2Fwww.baidu.com%2Flink%3Furl%3D7f5FbBhF-mRs1HPXrBCVKU_OweU60QlxumgnADAIgTO%26wd%3D%26eqid%3D86df049c0013d4af000000046048365a",
                    "csrf_token": "452a6317-b763-4356-a2ff-8875df178fbb",
                    "SESSION": "c72693b4-e875-4325-a121-eedfef6c560a",
                    "Hm_lpvt_4426cbb0486a79ea049b4ad52d81b504": "1615359773",
                    "_gat": "1",
                    "Jwt-Token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiNTYzNDEyMyIsImV4cCI6MTYxNzk1MTc4NSwiaWF0IjoxNjE1MzU5Nzg1fQ.TMaE3__PNoFYeCFvfsgTaHdzsGa9Oz5JgrTnJOb2Iw1FweZ9npAlghoYaUUaH0mQvPbqU83F5jBmHVv3OJv_lw",
                    "user_persistence": "8696b71b-a629-4dba-8a57-1398935cf2c1",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
        ),
        Step(
            RunRequest("/v3/api/user/profile")
            .post("https://api2.mubu.com/v3/api/user/profile")
            .with_headers(
                **{
                    "user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:86.0) Gecko/20100101 Firefox/86.0",
                    "accept": "application/json, text/plain, */*",
                    "accept-language": "zh-CN,zh;q=0.8,zh-TW;q=0.7,zh-HK;q=0.5,en-US;q=0.3,en;q=0.2",
                    "accept-encoding": "gzip, deflate, br",
                    "jwt-token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiNTYzNDEyMyIsImV4cCI6MTYxNzk1MTc4NSwiaWF0IjoxNjE1MzU5Nzg1fQ.TMaE3__PNoFYeCFvfsgTaHdzsGa9Oz5JgrTnJOb2Iw1FweZ9npAlghoYaUUaH0mQvPbqU83F5jBmHVv3OJv_lw",
                    "data-unique-id": "dc1ace1f-23f8-4634-bf93-07f9980b7fa0",
                    "x-request-id": "20b2b616-35d5-4bac-9883-cd08148f2a3a",
                    "version": "default",
                    "origin": "https://mubu.com",
                    "referer": "https://mubu.com/app",
                    "content-length": "0",
                    "te": "trailers",
                }
            )
            .with_data("")
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/list/star_relation/get")
            .get("https://api2.mubu.com/v3/api/list/star_relation/get")
            .with_headers(
                **{
                    "user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:86.0) Gecko/20100101 Firefox/86.0",
                    "accept": "application/json, text/plain, */*",
                    "accept-language": "zh-CN,zh;q=0.8,zh-TW;q=0.7,zh-HK;q=0.5,en-US;q=0.3,en;q=0.2",
                    "accept-encoding": "gzip, deflate, br",
                    "jwt-token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiNTYzNDEyMyIsImV4cCI6MTYxNzk1MTc4NSwiaWF0IjoxNjE1MzU5Nzg1fQ.TMaE3__PNoFYeCFvfsgTaHdzsGa9Oz5JgrTnJOb2Iw1FweZ9npAlghoYaUUaH0mQvPbqU83F5jBmHVv3OJv_lw",
                    "data-unique-id": "dc1ace1f-23f8-4634-bf93-07f9980b7fa0",
                    "x-request-id": "69caedb8-2925-4c00-8733-1d8d98007c9b",
                    "version": "default",
                    "origin": "https://mubu.com",
                    "referer": "https://mubu.com/app",
                    "te": "trailers",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/list/get_all_documents_page")
            .post("https://api2.mubu.com/v3/api/list/get_all_documents_page")
            .with_headers(
                **{
                    "user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:86.0) Gecko/20100101 Firefox/86.0",
                    "accept": "application/json, text/plain, */*",
                    "accept-language": "zh-CN,zh;q=0.8,zh-TW;q=0.7,zh-HK;q=0.5,en-US;q=0.3,en;q=0.2",
                    "accept-encoding": "gzip, deflate, br",
                    "content-type": "application/json;charset=utf-8",
                    "jwt-token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiNTYzNDEyMyIsImV4cCI6MTYxNzk1MTc4NSwiaWF0IjoxNjE1MzU5Nzg1fQ.TMaE3__PNoFYeCFvfsgTaHdzsGa9Oz5JgrTnJOb2Iw1FweZ9npAlghoYaUUaH0mQvPbqU83F5jBmHVv3OJv_lw",
                    "data-unique-id": "dc1ace1f-23f8-4634-bf93-07f9980b7fa0",
                    "x-request-id": "4a6d547d-06d6-49ee-8a04-877b107cb5e6",
                    "version": "default",
                    "content-length": "12",
                    "origin": "https://mubu.com",
                    "referer": "https://mubu.com/app",
                    "te": "trailers",
                }
            )
            .with_json({"start": ""})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/message/get_message_unread")
            .post("https://api2.mubu.com/v3/api/message/get_message_unread")
            .with_headers(
                **{
                    "user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:86.0) Gecko/20100101 Firefox/86.0",
                    "accept": "application/json, text/plain, */*",
                    "accept-language": "zh-CN,zh;q=0.8,zh-TW;q=0.7,zh-HK;q=0.5,en-US;q=0.3,en;q=0.2",
                    "accept-encoding": "gzip, deflate, br",
                    "content-type": "application/json;charset=utf-8",
                    "jwt-token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiNTYzNDEyMyIsImV4cCI6MTYxNzk1MTc4NSwiaWF0IjoxNjE1MzU5Nzg1fQ.TMaE3__PNoFYeCFvfsgTaHdzsGa9Oz5JgrTnJOb2Iw1FweZ9npAlghoYaUUaH0mQvPbqU83F5jBmHVv3OJv_lw",
                    "data-unique-id": "dc1ace1f-23f8-4634-bf93-07f9980b7fa0",
                    "x-request-id": "0b70a83e-2970-4f4e-b4ff-0d3a51bd8936",
                    "version": "default",
                    "content-length": "10",
                    "origin": "https://mubu.com",
                    "referer": "https://mubu.com/app",
                    "te": "trailers",
                }
            )
            .with_json({"page": 1})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/advertisement/get")
            .post("https://api2.mubu.com/v3/api/advertisement/get")
            .with_headers(
                **{
                    "user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:86.0) Gecko/20100101 Firefox/86.0",
                    "accept": "application/json, text/plain, */*",
                    "accept-language": "zh-CN,zh;q=0.8,zh-TW;q=0.7,zh-HK;q=0.5,en-US;q=0.3,en;q=0.2",
                    "accept-encoding": "gzip, deflate, br",
                    "content-type": "application/json;charset=utf-8",
                    "jwt-token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiNTYzNDEyMyIsImV4cCI6MTYxNzk1MTc4NSwiaWF0IjoxNjE1MzU5Nzg1fQ.TMaE3__PNoFYeCFvfsgTaHdzsGa9Oz5JgrTnJOb2Iw1FweZ9npAlghoYaUUaH0mQvPbqU83F5jBmHVv3OJv_lw",
                    "data-unique-id": "dc1ace1f-23f8-4634-bf93-07f9980b7fa0",
                    "x-request-id": "b75d9529-4fee-499c-a03e-60758b95ac23",
                    "version": "default",
                    "content-length": "10",
                    "origin": "https://mubu.com",
                    "referer": "https://mubu.com/app",
                    "te": "trailers",
                }
            )
            .with_json({"type": 1})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/list/item_count")
            .post("https://api2.mubu.com/v3/api/list/item_count")
            .with_headers(
                **{
                    "user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:86.0) Gecko/20100101 Firefox/86.0",
                    "accept": "application/json, text/plain, */*",
                    "accept-language": "zh-CN,zh;q=0.8,zh-TW;q=0.7,zh-HK;q=0.5,en-US;q=0.3,en;q=0.2",
                    "accept-encoding": "gzip, deflate, br",
                    "content-type": "application/json;charset=utf-8",
                    "jwt-token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiNTYzNDEyMyIsImV4cCI6MTYxNzk1MTc4NSwiaWF0IjoxNjE1MzU5Nzg1fQ.TMaE3__PNoFYeCFvfsgTaHdzsGa9Oz5JgrTnJOb2Iw1FweZ9npAlghoYaUUaH0mQvPbqU83F5jBmHVv3OJv_lw",
                    "data-unique-id": "dc1ace1f-23f8-4634-bf93-07f9980b7fa0",
                    "x-request-id": "6c144a91-e136-4481-b7d9-7c6ccadf4c5b",
                    "version": "default",
                    "content-length": "30",
                    "origin": "https://mubu.com",
                    "referer": "https://mubu.com/app",
                    "te": "trailers",
                }
            )
            .with_json({"folderId": 0, "source": "home"})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/user/get_user_params")
            .post("https://api2.mubu.com/v3/api/user/get_user_params")
            .with_headers(
                **{
                    "user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:86.0) Gecko/20100101 Firefox/86.0",
                    "accept": "application/json, text/plain, */*",
                    "accept-language": "zh-CN,zh;q=0.8,zh-TW;q=0.7,zh-HK;q=0.5,en-US;q=0.3,en;q=0.2",
                    "accept-encoding": "gzip, deflate, br",
                    "jwt-token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiNTYzNDEyMyIsImV4cCI6MTYxNzk1MTc4NSwiaWF0IjoxNjE1MzU5Nzg1fQ.TMaE3__PNoFYeCFvfsgTaHdzsGa9Oz5JgrTnJOb2Iw1FweZ9npAlghoYaUUaH0mQvPbqU83F5jBmHVv3OJv_lw",
                    "data-unique-id": "dc1ace1f-23f8-4634-bf93-07f9980b7fa0",
                    "x-request-id": "2864c9d1-effd-4883-93c1-71be26381757",
                    "version": "default",
                    "origin": "https://mubu.com",
                    "referer": "https://mubu.com/app",
                    "content-length": "0",
                    "te": "trailers",
                }
            )
            .with_data("")
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/list/create_doc")
            .options("https://api2.mubu.com/v3/api/list/create_doc")
            .with_headers(
                **{
                    "user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:86.0) Gecko/20100101 Firefox/86.0",
                    "accept": "*/*",
                    "accept-language": "zh-CN,zh;q=0.8,zh-TW;q=0.7,zh-HK;q=0.5,en-US;q=0.3,en;q=0.2",
                    "accept-encoding": "gzip, deflate, br",
                    "access-control-request-method": "POST",
                    "access-control-request-headers": "content-type,data-unique-id,jwt-token,version,x-request-id",
                    "referer": "https://mubu.com/app",
                    "origin": "https://mubu.com",
                    "te": "trailers",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
        ),
        Step(
            RunRequest("/v3/api/list/create_doc")
            .post("https://api2.mubu.com/v3/api/list/create_doc")
            .with_headers(
                **{
                    "user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:86.0) Gecko/20100101 Firefox/86.0",
                    "accept": "application/json, text/plain, */*",
                    "accept-language": "zh-CN,zh;q=0.8,zh-TW;q=0.7,zh-HK;q=0.5,en-US;q=0.3,en;q=0.2",
                    "accept-encoding": "gzip, deflate, br",
                    "content-type": "application/json;charset=utf-8",
                    "jwt-token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiNTYzNDEyMyIsImV4cCI6MTYxNzk1MTc4NSwiaWF0IjoxNjE1MzU5Nzg1fQ.TMaE3__PNoFYeCFvfsgTaHdzsGa9Oz5JgrTnJOb2Iw1FweZ9npAlghoYaUUaH0mQvPbqU83F5jBmHVv3OJv_lw",
                    "data-unique-id": "dc1ace1f-23f8-4634-bf93-07f9980b7fa0",
                    "x-request-id": "f4ee8fd3-43b8-47cb-9d80-6786d7d4313b",
                    "version": "default",
                    "content-length": "25",
                    "origin": "https://mubu.com",
                    "referer": "https://mubu.com/app",
                    "te": "trailers",
                }
            )
            .with_json({"folderId": "0", "type": 0})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/list/item_count")
            .post("https://api2.mubu.com/v3/api/list/item_count")
            .with_headers(
                **{
                    "user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:86.0) Gecko/20100101 Firefox/86.0",
                    "accept": "application/json, text/plain, */*",
                    "accept-language": "zh-CN,zh;q=0.8,zh-TW;q=0.7,zh-HK;q=0.5,en-US;q=0.3,en;q=0.2",
                    "accept-encoding": "gzip, deflate, br",
                    "content-type": "application/json;charset=utf-8",
                    "jwt-token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiNTYzNDEyMyIsImV4cCI6MTYxNzk1MTc4NSwiaWF0IjoxNjE1MzU5Nzg1fQ.TMaE3__PNoFYeCFvfsgTaHdzsGa9Oz5JgrTnJOb2Iw1FweZ9npAlghoYaUUaH0mQvPbqU83F5jBmHVv3OJv_lw",
                    "data-unique-id": "dc1ace1f-23f8-4634-bf93-07f9980b7fa0",
                    "x-request-id": "f7ce81b2-84ea-41e1-b97d-1a805d98becb",
                    "version": "default",
                    "content-length": "30",
                    "origin": "https://mubu.com",
                    "referer": "https://mubu.com/app/edit/home/40gQGtFLg5r",
                    "te": "trailers",
                }
            )
            .with_json({"folderId": 0, "source": "home"})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/user/current_level")
            .options("https://api2.mubu.com/v3/api/user/current_level")
            .with_headers(
                **{
                    "user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:86.0) Gecko/20100101 Firefox/86.0",
                    "accept": "*/*",
                    "accept-language": "zh-CN,zh;q=0.8,zh-TW;q=0.7,zh-HK;q=0.5,en-US;q=0.3,en;q=0.2",
                    "accept-encoding": "gzip, deflate, br",
                    "access-control-request-method": "POST",
                    "access-control-request-headers": "content-type,data-unique-id,jwt-token,version,x-request-id",
                    "referer": "https://mubu.com/app/edit/home/40gQGtFLg5r",
                    "origin": "https://mubu.com",
                    "te": "trailers",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
        ),
        Step(
            RunRequest("/v3/api/document/edit/get")
            .options("https://api2.mubu.com/v3/api/document/edit/get")
            .with_headers(
                **{
                    "user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:86.0) Gecko/20100101 Firefox/86.0",
                    "accept": "*/*",
                    "accept-language": "zh-CN,zh;q=0.8,zh-TW;q=0.7,zh-HK;q=0.5,en-US;q=0.3,en;q=0.2",
                    "accept-encoding": "gzip, deflate, br",
                    "access-control-request-method": "POST",
                    "access-control-request-headers": "content-type,data-unique-id,jwt-token,version,x-request-id",
                    "referer": "https://mubu.com/app/edit/home/40gQGtFLg5r",
                    "origin": "https://mubu.com",
                    "te": "trailers",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
        ),
        Step(
            RunRequest("/v3/api/user/current_level")
            .post("https://api2.mubu.com/v3/api/user/current_level")
            .with_headers(
                **{
                    "user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:86.0) Gecko/20100101 Firefox/86.0",
                    "accept": "application/json, text/plain, */*",
                    "accept-language": "zh-CN,zh;q=0.8,zh-TW;q=0.7,zh-HK;q=0.5,en-US;q=0.3,en;q=0.2",
                    "accept-encoding": "gzip, deflate, br",
                    "content-type": "application/json;charset=utf-8",
                    "jwt-token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiNTYzNDEyMyIsImV4cCI6MTYxNzk1MTc4NSwiaWF0IjoxNjE1MzU5Nzg1fQ.TMaE3__PNoFYeCFvfsgTaHdzsGa9Oz5JgrTnJOb2Iw1FweZ9npAlghoYaUUaH0mQvPbqU83F5jBmHVv3OJv_lw",
                    "data-unique-id": "dc1ace1f-23f8-4634-bf93-07f9980b7fa0",
                    "x-request-id": "41709a7a-2434-4130-b92e-e46740aed261",
                    "version": "default",
                    "content-length": "29",
                    "origin": "https://mubu.com",
                    "referer": "https://mubu.com/app/edit/home/40gQGtFLg5r",
                    "te": "trailers",
                }
            )
            .with_json({"document_id": "40gQGtFLg5r"})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/document/edit/get")
            .post("https://api2.mubu.com/v3/api/document/edit/get")
            .with_headers(
                **{
                    "user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:86.0) Gecko/20100101 Firefox/86.0",
                    "accept": "application/json, text/plain, */*",
                    "accept-language": "zh-CN,zh;q=0.8,zh-TW;q=0.7,zh-HK;q=0.5,en-US;q=0.3,en;q=0.2",
                    "accept-encoding": "gzip, deflate, br",
                    "content-type": "application/json;charset=utf-8",
                    "jwt-token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiNTYzNDEyMyIsImV4cCI6MTYxNzk1MTc4NSwiaWF0IjoxNjE1MzU5Nzg1fQ.TMaE3__PNoFYeCFvfsgTaHdzsGa9Oz5JgrTnJOb2Iw1FweZ9npAlghoYaUUaH0mQvPbqU83F5jBmHVv3OJv_lw",
                    "data-unique-id": "dc1ace1f-23f8-4634-bf93-07f9980b7fa0",
                    "x-request-id": "dfc12101-e364-459e-b14f-e71a5b5213e8",
                    "version": "default",
                    "content-length": "37",
                    "origin": "https://mubu.com",
                    "referer": "https://mubu.com/app/edit/home/40gQGtFLg5r",
                    "te": "trailers",
                }
            )
            .with_json({"docId": "40gQGtFLg5r", "password": ""})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/refer/doc/list")
            .options("https://api2.mubu.com/v3/api/refer/doc/list")
            .with_headers(
                **{
                    "user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:86.0) Gecko/20100101 Firefox/86.0",
                    "accept": "*/*",
                    "accept-language": "zh-CN,zh;q=0.8,zh-TW;q=0.7,zh-HK;q=0.5,en-US;q=0.3,en;q=0.2",
                    "accept-encoding": "gzip, deflate, br",
                    "access-control-request-method": "POST",
                    "access-control-request-headers": "content-type,data-unique-id,jwt-token,x-request-id",
                    "referer": "https://mubu.com/app/edit/home/40gQGtFLg5r",
                    "origin": "https://mubu.com",
                    "te": "trailers",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
        ),
        Step(
            RunRequest("/v3/api/colla/register")
            .options("https://api2.mubu.com/v3/api/colla/register")
            .with_headers(
                **{
                    "user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:86.0) Gecko/20100101 Firefox/86.0",
                    "accept": "*/*",
                    "accept-language": "zh-CN,zh;q=0.8,zh-TW;q=0.7,zh-HK;q=0.5,en-US;q=0.3,en;q=0.2",
                    "accept-encoding": "gzip, deflate, br",
                    "access-control-request-method": "GET",
                    "access-control-request-headers": "data-unique-id,jwt-token,x-request-id",
                    "referer": "https://mubu.com/app/edit/home/40gQGtFLg5r",
                    "origin": "https://mubu.com",
                    "te": "trailers",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
        ),
        Step(
            RunRequest("/v3/api/refer/doc/list")
            .post("https://api2.mubu.com/v3/api/refer/doc/list")
            .with_headers(
                **{
                    "user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:86.0) Gecko/20100101 Firefox/86.0",
                    "accept": "application/json, text/plain, */*",
                    "accept-language": "zh-CN,zh;q=0.8,zh-TW;q=0.7,zh-HK;q=0.5,en-US;q=0.3,en;q=0.2",
                    "accept-encoding": "gzip, deflate, br",
                    "content-type": "application/json;charset=utf-8",
                    "jwt-token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiNTYzNDEyMyIsImV4cCI6MTYxNzk1MTc4NSwiaWF0IjoxNjE1MzU5Nzg1fQ.TMaE3__PNoFYeCFvfsgTaHdzsGa9Oz5JgrTnJOb2Iw1FweZ9npAlghoYaUUaH0mQvPbqU83F5jBmHVv3OJv_lw",
                    "data-unique-id": "dc1ace1f-23f8-4634-bf93-07f9980b7fa0",
                    "x-request-id": "72c041c3-f795-4e53-b036-85bfb091067f",
                    "content-length": "29",
                    "origin": "https://mubu.com",
                    "referer": "https://mubu.com/app/edit/home/40gQGtFLg5r",
                    "te": "trailers",
                }
            )
            .with_json({"targetDocId": "40gQGtFLg5r"})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/colla/register")
            .get("https://api2.mubu.com/v3/api/colla/register")
            .with_headers(
                **{
                    "user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:86.0) Gecko/20100101 Firefox/86.0",
                    "accept": "application/json, text/plain, */*",
                    "accept-language": "zh-CN,zh;q=0.8,zh-TW;q=0.7,zh-HK;q=0.5,en-US;q=0.3,en;q=0.2",
                    "accept-encoding": "gzip, deflate, br",
                    "jwt-token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiNTYzNDEyMyIsImV4cCI6MTYxNzk1MTc4NSwiaWF0IjoxNjE1MzU5Nzg1fQ.TMaE3__PNoFYeCFvfsgTaHdzsGa9Oz5JgrTnJOb2Iw1FweZ9npAlghoYaUUaH0mQvPbqU83F5jBmHVv3OJv_lw",
                    "data-unique-id": "dc1ace1f-23f8-4634-bf93-07f9980b7fa0",
                    "x-request-id": "a711db9a-ef90-4444-b401-00e6f4aa328d",
                    "origin": "https://mubu.com",
                    "referer": "https://mubu.com/app/edit/home/40gQGtFLg5r",
                    "te": "trailers",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/colla/members")
            .options("https://api2.mubu.com/v3/api/colla/members")
            .with_params(
                **{"memberId": "2654354234878869", "documentId": "40gQGtFLg5r"}
            )
            .with_headers(
                **{
                    "user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:86.0) Gecko/20100101 Firefox/86.0",
                    "accept": "*/*",
                    "accept-language": "zh-CN,zh;q=0.8,zh-TW;q=0.7,zh-HK;q=0.5,en-US;q=0.3,en;q=0.2",
                    "accept-encoding": "gzip, deflate, br",
                    "access-control-request-method": "GET",
                    "access-control-request-headers": "data-unique-id,jwt-token,request-id,x-request-id",
                    "referer": "https://mubu.com/app/edit/home/40gQGtFLg5r",
                    "origin": "https://mubu.com",
                    "te": "trailers",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
        ),
        Step(
            RunRequest("/v3/api/colla/members")
            .get("https://api2.mubu.com/v3/api/colla/members")
            .with_params(
                **{"memberId": "2654354234878869", "documentId": "40gQGtFLg5r"}
            )
            .with_headers(
                **{
                    "user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:86.0) Gecko/20100101 Firefox/86.0",
                    "accept": "application/json, text/plain, */*",
                    "accept-language": "zh-CN,zh;q=0.8,zh-TW;q=0.7,zh-HK;q=0.5,en-US;q=0.3,en;q=0.2",
                    "accept-encoding": "gzip, deflate, br",
                    "jwt-token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiNTYzNDEyMyIsImV4cCI6MTYxNzk1MTc4NSwiaWF0IjoxNjE1MzU5Nzg1fQ.TMaE3__PNoFYeCFvfsgTaHdzsGa9Oz5JgrTnJOb2Iw1FweZ9npAlghoYaUUaH0mQvPbqU83F5jBmHVv3OJv_lw",
                    "data-unique-id": "dc1ace1f-23f8-4634-bf93-07f9980b7fa0",
                    "x-request-id": "25d55d3a-91e1-4be2-b044-1f80dd0c5cd5",
                    "request-id": "members:2654354234878869:1615359793370",
                    "origin": "https://mubu.com",
                    "referer": "https://mubu.com/app/edit/home/40gQGtFLg5r",
                    "te": "trailers",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/sync/meta_v2")
            .post("https://api2.mubu.com/v3/api/sync/meta_v2")
            .with_headers(
                **{
                    "content-length": "89",
                    "accept": "application/json, text/plain;q=0.9",
                    "content-type": "application/json; charset=utf-8",
                    "user-agent": "windows Mubu Electron",
                    "jwt-token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiNTYzNDEyMyIsImxvZ2luVHlwZSI6IndlaXhpbiIsImlhdCI6MTYxNDY0Nzc1NH0.tdY4nhpdfF6QYXRCZNYvai9jnOZ17s405MOUpmdSFeI5Snywn6gkfOseHhA5Zmw8FiGDlrhCCWPsoOmSxDg-kQ",
                    "mubu-desktop": "true",
                    "platform": "win32",
                    "platform-version": "10.0.18363",
                    "token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiNTYzNDEyMyIsImxvZ2luVHlwZSI6IndlaXhpbiIsImlhdCI6MTYxNDY0Nzc1NH0.tdY4nhpdfF6QYXRCZNYvai9jnOZ17s405MOUpmdSFeI5Snywn6gkfOseHhA5Zmw8FiGDlrhCCWPsoOmSxDg-kQ",
                    "version": "3.0.2",
                    "sec-fetch-site": "none",
                    "sec-fetch-mode": "no-cors",
                    "sec-fetch-dest": "empty",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN",
                }
            )
            .with_json(
                {
                    "masterVersion": 1615359755612,
                    "modification": [],
                    "sourceFolders": {},
                    "sourceDocuments": {},
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/ping")
            .get("https://api2.mubu.com/v3/api/ping")
            .with_headers(
                **{
                    "jwt-token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiNTYzNDEyMyIsImxvZ2luVHlwZSI6IndlaXhpbiIsImlhdCI6MTYxNDY0Nzc1NH0.tdY4nhpdfF6QYXRCZNYvai9jnOZ17s405MOUpmdSFeI5Snywn6gkfOseHhA5Zmw8FiGDlrhCCWPsoOmSxDg-kQ",
                    "mubu-desktop": "true",
                    "platform": "win32",
                    "version": "3.0.2",
                    "sec-fetch-site": "none",
                    "sec-fetch-mode": "no-cors",
                    "sec-fetch-dest": "empty",
                    "user-agent": "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) å¹\x95å¸\x83/3.0.2 Chrome/83.0.4103.122 Electron/9.3.0 Safari/537.36",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN",
                }
            )
            .validate()
            .assert_equal("status_code", 204)
        ),
        Step(
            RunRequest("/v3/api/colla/message")
            .options("https://api2.mubu.com/v3/api/colla/message")
            .with_headers(
                **{
                    "user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:86.0) Gecko/20100101 Firefox/86.0",
                    "accept": "*/*",
                    "accept-language": "zh-CN,zh;q=0.8,zh-TW;q=0.7,zh-HK;q=0.5,en-US;q=0.3,en;q=0.2",
                    "accept-encoding": "gzip, deflate, br",
                    "access-control-request-method": "POST",
                    "access-control-request-headers": "content-type,data-unique-id,jwt-token,member-id,request-id,version,x-request-id",
                    "referer": "https://mubu.com/app/edit/home/40gQGtFLg5r",
                    "origin": "https://mubu.com",
                    "te": "trailers",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
        ),
        Step(
            RunRequest("/v3/api/colla/message")
            .post("https://api2.mubu.com/v3/api/colla/message")
            .with_headers(
                **{
                    "user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:86.0) Gecko/20100101 Firefox/86.0",
                    "accept": "application/json, text/plain, */*",
                    "accept-language": "zh-CN,zh;q=0.8,zh-TW;q=0.7,zh-HK;q=0.5,en-US;q=0.3,en;q=0.2",
                    "accept-encoding": "gzip, deflate, br",
                    "content-type": "application/json;charset=utf-8",
                    "jwt-token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiNTYzNDEyMyIsImV4cCI6MTYxNzk1MTc4NSwiaWF0IjoxNjE1MzU5Nzg1fQ.TMaE3__PNoFYeCFvfsgTaHdzsGa9Oz5JgrTnJOb2Iw1FweZ9npAlghoYaUUaH0mQvPbqU83F5jBmHVv3OJv_lw",
                    "data-unique-id": "dc1ace1f-23f8-4634-bf93-07f9980b7fa0",
                    "x-request-id": "8405e4e3-756f-4fca-bdd2-4b75fe40006a",
                    "request-id": "MESSAGE:5634123:2654354234878869:3",
                    "member-id": "2654354234878869",
                    "version": "3.0.0",
                    "content-length": "425",
                    "origin": "https://mubu.com",
                    "referer": "https://mubu.com/app/edit/home/40gQGtFLg5r",
                    "te": "trailers",
                }
            )
            .with_json(
                {
                    "engineType": "MUBU",
                    "messageType": "BROADCAST",
                    "reqId": 3,
                    "requestId": "MESSAGE:5634123:2654354234878869:3",
                    "token": "40gQGtFLg5r",
                    "data": {
                        "message": {
                            "type": "CHANGE",
                            "documentId": "40gQGtFLg5r",
                            "version": 0,
                            "content": [
                                {
                                    "name": "nameChanged",
                                    "title": "testdemo",
                                    "original": "",
                                },
                                {
                                    "name": "nameChanged",
                                    "title": "testdemo",
                                    "original": "testdemo",
                                },
                            ],
                        }
                    },
                    "context": {
                        "os": "Windows",
                        "osVersion": "NT 10.0",
                        "appVersion": "default",
                        "platform": "web",
                    },
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/colla/message")
            .post("https://api2.mubu.com/v3/api/colla/message")
            .with_headers(
                **{
                    "user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:86.0) Gecko/20100101 Firefox/86.0",
                    "accept": "application/json, text/plain, */*",
                    "accept-language": "zh-CN,zh;q=0.8,zh-TW;q=0.7,zh-HK;q=0.5,en-US;q=0.3,en;q=0.2",
                    "accept-encoding": "gzip, deflate, br",
                    "content-type": "application/json;charset=utf-8",
                    "jwt-token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiNTYzNDEyMyIsImV4cCI6MTYxNzk1MTc4NSwiaWF0IjoxNjE1MzU5Nzg1fQ.TMaE3__PNoFYeCFvfsgTaHdzsGa9Oz5JgrTnJOb2Iw1FweZ9npAlghoYaUUaH0mQvPbqU83F5jBmHVv3OJv_lw",
                    "data-unique-id": "dc1ace1f-23f8-4634-bf93-07f9980b7fa0",
                    "x-request-id": "380cfc94-9a7a-459b-8bdf-f1d8e3df0445",
                    "request-id": "MESSAGE:5634123:2654354234878869:5",
                    "member-id": "2654354234878869",
                    "version": "3.0.0",
                    "content-length": "458",
                    "origin": "https://mubu.com",
                    "referer": "https://mubu.com/app/edit/home/40gQGtFLg5r",
                    "te": "trailers",
                }
            )
            .with_json(
                {
                    "engineType": "MUBU",
                    "messageType": "BROADCAST",
                    "reqId": 5,
                    "requestId": "MESSAGE:5634123:2654354234878869:5",
                    "token": "40gQGtFLg5r",
                    "data": {
                        "message": {
                            "type": "CHANGE",
                            "documentId": "40gQGtFLg5r",
                            "version": 1,
                            "content": [
                                {
                                    "name": "create",
                                    "created": [
                                        {
                                            "index": 0,
                                            "parentId": None,
                                            "node": {
                                                "id": "6j1N2tyNP6",
                                                "text": "",
                                                "modified": 1615359798218,
                                                "children": [],
                                            },
                                            "path": ["nodes", 0],
                                        }
                                    ],
                                }
                            ],
                        }
                    },
                    "context": {
                        "os": "Windows",
                        "osVersion": "NT 10.0",
                        "appVersion": "default",
                        "platform": "web",
                    },
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/refer/search_refers")
            .options("https://api2.mubu.com/v3/api/refer/search_refers")
            .with_headers(
                **{
                    "user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:86.0) Gecko/20100101 Firefox/86.0",
                    "accept": "*/*",
                    "accept-language": "zh-CN,zh;q=0.8,zh-TW;q=0.7,zh-HK;q=0.5,en-US;q=0.3,en;q=0.2",
                    "accept-encoding": "gzip, deflate, br",
                    "access-control-request-method": "POST",
                    "access-control-request-headers": "content-type,data-unique-id,jwt-token,x-request-id",
                    "referer": "https://mubu.com/app/edit/home/40gQGtFLg5r",
                    "origin": "https://mubu.com",
                    "te": "trailers",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
        ),
        Step(
            RunRequest("/v3/api/refer/search_refers")
            .post("https://api2.mubu.com/v3/api/refer/search_refers")
            .with_headers(
                **{
                    "user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:86.0) Gecko/20100101 Firefox/86.0",
                    "accept": "application/json, text/plain, */*",
                    "accept-language": "zh-CN,zh;q=0.8,zh-TW;q=0.7,zh-HK;q=0.5,en-US;q=0.3,en;q=0.2",
                    "accept-encoding": "gzip, deflate, br",
                    "content-type": "application/json;charset=utf-8",
                    "jwt-token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiNTYzNDEyMyIsImV4cCI6MTYxNzk1MTc4NSwiaWF0IjoxNjE1MzU5Nzg1fQ.TMaE3__PNoFYeCFvfsgTaHdzsGa9Oz5JgrTnJOb2Iw1FweZ9npAlghoYaUUaH0mQvPbqU83F5jBmHVv3OJv_lw",
                    "data-unique-id": "dc1ace1f-23f8-4634-bf93-07f9980b7fa0",
                    "x-request-id": "5dd07b9a-0a64-435a-9e4e-642741fef235",
                    "content-length": "56",
                    "origin": "https://mubu.com",
                    "referer": "https://mubu.com/app/edit/home/40gQGtFLg5r",
                    "te": "trailers",
                }
            )
            .with_json({"docId": "40gQGtFLg5r", "keywords": "testdemo", "option": 1})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/colla/message")
            .post("https://api2.mubu.com/v3/api/colla/message")
            .with_headers(
                **{
                    "user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:86.0) Gecko/20100101 Firefox/86.0",
                    "accept": "application/json, text/plain, */*",
                    "accept-language": "zh-CN,zh;q=0.8,zh-TW;q=0.7,zh-HK;q=0.5,en-US;q=0.3,en;q=0.2",
                    "accept-encoding": "gzip, deflate, br",
                    "content-type": "application/json;charset=utf-8",
                    "jwt-token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiNTYzNDEyMyIsImV4cCI6MTYxNzk1MTc4NSwiaWF0IjoxNjE1MzU5Nzg1fQ.TMaE3__PNoFYeCFvfsgTaHdzsGa9Oz5JgrTnJOb2Iw1FweZ9npAlghoYaUUaH0mQvPbqU83F5jBmHVv3OJv_lw",
                    "data-unique-id": "dc1ace1f-23f8-4634-bf93-07f9980b7fa0",
                    "x-request-id": "67f4dba7-b94a-47b7-9e46-be021a55d33c",
                    "request-id": "MESSAGE:5634123:2654354234878869:7",
                    "member-id": "2654354234878869",
                    "version": "3.0.0",
                    "content-length": "503",
                    "origin": "https://mubu.com",
                    "referer": "https://mubu.com/app/edit/home/40gQGtFLg5r",
                    "te": "trailers",
                }
            )
            .with_json(
                {
                    "engineType": "MUBU",
                    "messageType": "BROADCAST",
                    "reqId": 7,
                    "requestId": "MESSAGE:5634123:2654354234878869:7",
                    "token": "40gQGtFLg5r",
                    "data": {
                        "message": {
                            "type": "CHANGE",
                            "documentId": "40gQGtFLg5r",
                            "version": 2,
                            "content": [
                                {
                                    "name": "update",
                                    "updated": [
                                        {
                                            "updated": {
                                                "id": "6j1N2tyNP6",
                                                "text": "<span>111</span>",
                                                "modified": 1615359799870,
                                            },
                                            "original": {
                                                "id": "6j1N2tyNP6",
                                                "text": "",
                                                "modified": 1615359798218,
                                            },
                                            "path": ["nodes", 0],
                                        }
                                    ],
                                }
                            ],
                        }
                    },
                    "context": {
                        "os": "Windows",
                        "osVersion": "NT 10.0",
                        "appVersion": "default",
                        "platform": "web",
                    },
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/colla/message")
            .post("https://api2.mubu.com/v3/api/colla/message")
            .with_headers(
                **{
                    "user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:86.0) Gecko/20100101 Firefox/86.0",
                    "accept": "application/json, text/plain, */*",
                    "accept-language": "zh-CN,zh;q=0.8,zh-TW;q=0.7,zh-HK;q=0.5,en-US;q=0.3,en;q=0.2",
                    "accept-encoding": "gzip, deflate, br",
                    "content-type": "application/json;charset=utf-8",
                    "jwt-token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiNTYzNDEyMyIsImV4cCI6MTYxNzk1MTc4NSwiaWF0IjoxNjE1MzU5Nzg1fQ.TMaE3__PNoFYeCFvfsgTaHdzsGa9Oz5JgrTnJOb2Iw1FweZ9npAlghoYaUUaH0mQvPbqU83F5jBmHVv3OJv_lw",
                    "data-unique-id": "dc1ace1f-23f8-4634-bf93-07f9980b7fa0",
                    "x-request-id": "04c6c5fb-6cae-4774-b45f-9133cd4e9a40",
                    "request-id": "MESSAGE:5634123:2654354234878869:9",
                    "member-id": "2654354234878869",
                    "version": "3.0.0",
                    "content-length": "458",
                    "origin": "https://mubu.com",
                    "referer": "https://mubu.com/app/edit/home/40gQGtFLg5r",
                    "te": "trailers",
                }
            )
            .with_json(
                {
                    "engineType": "MUBU",
                    "messageType": "BROADCAST",
                    "reqId": 9,
                    "requestId": "MESSAGE:5634123:2654354234878869:9",
                    "token": "40gQGtFLg5r",
                    "data": {
                        "message": {
                            "type": "CHANGE",
                            "documentId": "40gQGtFLg5r",
                            "version": 3,
                            "content": [
                                {
                                    "name": "create",
                                    "created": [
                                        {
                                            "index": 1,
                                            "parentId": None,
                                            "node": {
                                                "id": "CGqwbAdYHq",
                                                "text": "",
                                                "modified": 1615359800299,
                                                "children": [],
                                            },
                                            "path": ["nodes", 1],
                                        }
                                    ],
                                }
                            ],
                        }
                    },
                    "context": {
                        "os": "Windows",
                        "osVersion": "NT 10.0",
                        "appVersion": "default",
                        "platform": "web",
                    },
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/colla/message")
            .post("https://api2.mubu.com/v3/api/colla/message")
            .with_headers(
                **{
                    "user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:86.0) Gecko/20100101 Firefox/86.0",
                    "accept": "application/json, text/plain, */*",
                    "accept-language": "zh-CN,zh;q=0.8,zh-TW;q=0.7,zh-HK;q=0.5,en-US;q=0.3,en;q=0.2",
                    "accept-encoding": "gzip, deflate, br",
                    "content-type": "application/json;charset=utf-8",
                    "jwt-token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiNTYzNDEyMyIsImV4cCI6MTYxNzk1MTc4NSwiaWF0IjoxNjE1MzU5Nzg1fQ.TMaE3__PNoFYeCFvfsgTaHdzsGa9Oz5JgrTnJOb2Iw1FweZ9npAlghoYaUUaH0mQvPbqU83F5jBmHVv3OJv_lw",
                    "data-unique-id": "dc1ace1f-23f8-4634-bf93-07f9980b7fa0",
                    "x-request-id": "35f59937-fe2d-4de6-b63b-1613aab8a383",
                    "request-id": "MESSAGE:5634123:2654354234878869:11",
                    "member-id": "2654354234878869",
                    "version": "3.0.0",
                    "content-length": "504",
                    "origin": "https://mubu.com",
                    "referer": "https://mubu.com/app/edit/home/40gQGtFLg5r",
                    "te": "trailers",
                }
            )
            .with_json(
                {
                    "engineType": "MUBU",
                    "messageType": "BROADCAST",
                    "reqId": 11,
                    "requestId": "MESSAGE:5634123:2654354234878869:11",
                    "token": "40gQGtFLg5r",
                    "data": {
                        "message": {
                            "type": "CHANGE",
                            "documentId": "40gQGtFLg5r",
                            "version": 4,
                            "content": [
                                {
                                    "name": "update",
                                    "updated": [
                                        {
                                            "updated": {
                                                "id": "CGqwbAdYHq",
                                                "text": "<span>22</span>",
                                                "modified": 1615359801004,
                                            },
                                            "original": {
                                                "id": "CGqwbAdYHq",
                                                "text": "",
                                                "modified": 1615359800299,
                                            },
                                            "path": ["nodes", 1],
                                        }
                                    ],
                                }
                            ],
                        }
                    },
                    "context": {
                        "os": "Windows",
                        "osVersion": "NT 10.0",
                        "appVersion": "default",
                        "platform": "web",
                    },
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/colla/message")
            .post("https://api2.mubu.com/v3/api/colla/message")
            .with_headers(
                **{
                    "user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:86.0) Gecko/20100101 Firefox/86.0",
                    "accept": "application/json, text/plain, */*",
                    "accept-language": "zh-CN,zh;q=0.8,zh-TW;q=0.7,zh-HK;q=0.5,en-US;q=0.3,en;q=0.2",
                    "accept-encoding": "gzip, deflate, br",
                    "content-type": "application/json;charset=utf-8",
                    "jwt-token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiNTYzNDEyMyIsImV4cCI6MTYxNzk1MTc4NSwiaWF0IjoxNjE1MzU5Nzg1fQ.TMaE3__PNoFYeCFvfsgTaHdzsGa9Oz5JgrTnJOb2Iw1FweZ9npAlghoYaUUaH0mQvPbqU83F5jBmHVv3OJv_lw",
                    "data-unique-id": "dc1ace1f-23f8-4634-bf93-07f9980b7fa0",
                    "x-request-id": "a7fd572c-9abc-4a18-afed-28939fe69d7c",
                    "request-id": "MESSAGE:5634123:2654354234878869:13",
                    "member-id": "2654354234878869",
                    "version": "3.0.0",
                    "content-length": "520",
                    "origin": "https://mubu.com",
                    "referer": "https://mubu.com/app/edit/home/40gQGtFLg5r",
                    "te": "trailers",
                }
            )
            .with_json(
                {
                    "engineType": "MUBU",
                    "messageType": "BROADCAST",
                    "reqId": 13,
                    "requestId": "MESSAGE:5634123:2654354234878869:13",
                    "token": "40gQGtFLg5r",
                    "data": {
                        "message": {
                            "type": "CHANGE",
                            "documentId": "40gQGtFLg5r",
                            "version": 5,
                            "content": [
                                {
                                    "name": "update",
                                    "updated": [
                                        {
                                            "updated": {
                                                "id": "CGqwbAdYHq",
                                                "text": "<span>222</span>",
                                                "modified": 1615359801244,
                                            },
                                            "original": {
                                                "id": "CGqwbAdYHq",
                                                "text": "<span>22</span>",
                                                "modified": 1615359801004,
                                            },
                                            "path": ["nodes", 1],
                                        }
                                    ],
                                }
                            ],
                        }
                    },
                    "context": {
                        "os": "Windows",
                        "osVersion": "NT 10.0",
                        "appVersion": "default",
                        "platform": "web",
                    },
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/colla/message")
            .post("https://api2.mubu.com/v3/api/colla/message")
            .with_headers(
                **{
                    "user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:86.0) Gecko/20100101 Firefox/86.0",
                    "accept": "application/json, text/plain, */*",
                    "accept-language": "zh-CN,zh;q=0.8,zh-TW;q=0.7,zh-HK;q=0.5,en-US;q=0.3,en;q=0.2",
                    "accept-encoding": "gzip, deflate, br",
                    "content-type": "application/json;charset=utf-8",
                    "jwt-token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiNTYzNDEyMyIsImV4cCI6MTYxNzk1MTc4NSwiaWF0IjoxNjE1MzU5Nzg1fQ.TMaE3__PNoFYeCFvfsgTaHdzsGa9Oz5JgrTnJOb2Iw1FweZ9npAlghoYaUUaH0mQvPbqU83F5jBmHVv3OJv_lw",
                    "data-unique-id": "dc1ace1f-23f8-4634-bf93-07f9980b7fa0",
                    "x-request-id": "d3bf5d84-8a37-492e-8428-643f9611aa46",
                    "request-id": "MESSAGE:5634123:2654354234878869:14",
                    "member-id": "2654354234878869",
                    "version": "3.0.0",
                    "content-length": "460",
                    "origin": "https://mubu.com",
                    "referer": "https://mubu.com/app/edit/home/40gQGtFLg5r",
                    "te": "trailers",
                }
            )
            .with_json(
                {
                    "engineType": "MUBU",
                    "messageType": "BROADCAST",
                    "reqId": 14,
                    "requestId": "MESSAGE:5634123:2654354234878869:14",
                    "token": "40gQGtFLg5r",
                    "data": {
                        "message": {
                            "type": "CHANGE",
                            "documentId": "40gQGtFLg5r",
                            "version": 6,
                            "content": [
                                {
                                    "name": "create",
                                    "created": [
                                        {
                                            "index": 2,
                                            "parentId": None,
                                            "node": {
                                                "id": "4QjLn6hPi1",
                                                "text": "",
                                                "modified": 1615359801977,
                                                "children": [],
                                            },
                                            "path": ["nodes", 2],
                                        }
                                    ],
                                }
                            ],
                        }
                    },
                    "context": {
                        "os": "Windows",
                        "osVersion": "NT 10.0",
                        "appVersion": "default",
                        "platform": "web",
                    },
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/colla/message")
            .post("https://api2.mubu.com/v3/api/colla/message")
            .with_headers(
                **{
                    "user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:86.0) Gecko/20100101 Firefox/86.0",
                    "accept": "application/json, text/plain, */*",
                    "accept-language": "zh-CN,zh;q=0.8,zh-TW;q=0.7,zh-HK;q=0.5,en-US;q=0.3,en;q=0.2",
                    "accept-encoding": "gzip, deflate, br",
                    "content-type": "application/json;charset=utf-8",
                    "jwt-token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiNTYzNDEyMyIsImV4cCI6MTYxNzk1MTc4NSwiaWF0IjoxNjE1MzU5Nzg1fQ.TMaE3__PNoFYeCFvfsgTaHdzsGa9Oz5JgrTnJOb2Iw1FweZ9npAlghoYaUUaH0mQvPbqU83F5jBmHVv3OJv_lw",
                    "data-unique-id": "dc1ace1f-23f8-4634-bf93-07f9980b7fa0",
                    "x-request-id": "a1f5a55f-fe60-4474-a3e7-3e72b357ce73",
                    "request-id": "MESSAGE:5634123:2654354234878869:16",
                    "member-id": "2654354234878869",
                    "version": "3.0.0",
                    "content-length": "505",
                    "origin": "https://mubu.com",
                    "referer": "https://mubu.com/app/edit/home/40gQGtFLg5r",
                    "te": "trailers",
                }
            )
            .with_json(
                {
                    "engineType": "MUBU",
                    "messageType": "BROADCAST",
                    "reqId": 16,
                    "requestId": "MESSAGE:5634123:2654354234878869:16",
                    "token": "40gQGtFLg5r",
                    "data": {
                        "message": {
                            "type": "CHANGE",
                            "documentId": "40gQGtFLg5r",
                            "version": 7,
                            "content": [
                                {
                                    "name": "update",
                                    "updated": [
                                        {
                                            "updated": {
                                                "id": "4QjLn6hPi1",
                                                "text": "<span>333</span>",
                                                "modified": 1615359802880,
                                            },
                                            "original": {
                                                "id": "4QjLn6hPi1",
                                                "text": "",
                                                "modified": 1615359801977,
                                            },
                                            "path": ["nodes", 2],
                                        }
                                    ],
                                }
                            ],
                        }
                    },
                    "context": {
                        "os": "Windows",
                        "osVersion": "NT 10.0",
                        "appVersion": "default",
                        "platform": "web",
                    },
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/list/item_count")
            .post("https://api2.mubu.com/v3/api/list/item_count")
            .with_headers(
                **{
                    "user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:86.0) Gecko/20100101 Firefox/86.0",
                    "accept": "application/json, text/plain, */*",
                    "accept-language": "zh-CN,zh;q=0.8,zh-TW;q=0.7,zh-HK;q=0.5,en-US;q=0.3,en;q=0.2",
                    "accept-encoding": "gzip, deflate, br",
                    "content-type": "application/json;charset=utf-8",
                    "jwt-token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiNTYzNDEyMyIsImV4cCI6MTYxNzk1MTc4NSwiaWF0IjoxNjE1MzU5Nzg1fQ.TMaE3__PNoFYeCFvfsgTaHdzsGa9Oz5JgrTnJOb2Iw1FweZ9npAlghoYaUUaH0mQvPbqU83F5jBmHVv3OJv_lw",
                    "data-unique-id": "dc1ace1f-23f8-4634-bf93-07f9980b7fa0",
                    "x-request-id": "984376f0-ed86-4ee2-aee6-4c95bc748134",
                    "version": "default",
                    "content-length": "30",
                    "origin": "https://mubu.com",
                    "referer": "https://mubu.com/app",
                    "te": "trailers",
                }
            )
            .with_json({"folderId": 0, "source": "home"})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/colla/message")
            .post("https://api2.mubu.com/v3/api/colla/message")
            .with_headers(
                **{
                    "user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:86.0) Gecko/20100101 Firefox/86.0",
                    "accept": "application/json, text/plain, */*",
                    "accept-language": "zh-CN,zh;q=0.8,zh-TW;q=0.7,zh-HK;q=0.5,en-US;q=0.3,en;q=0.2",
                    "accept-encoding": "gzip, deflate, br",
                    "content-type": "application/json;charset=utf-8",
                    "jwt-token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiNTYzNDEyMyIsImV4cCI6MTYxNzk1MTc4NSwiaWF0IjoxNjE1MzU5Nzg1fQ.TMaE3__PNoFYeCFvfsgTaHdzsGa9Oz5JgrTnJOb2Iw1FweZ9npAlghoYaUUaH0mQvPbqU83F5jBmHVv3OJv_lw",
                    "data-unique-id": "dc1ace1f-23f8-4634-bf93-07f9980b7fa0",
                    "x-request-id": "4b67b742-9df9-4ced-8a8f-7f9fa726f8d9",
                    "request-id": "MESSAGE:5634123:2654354234878869:18",
                    "member-id": "2654354234878869",
                    "version": "3.0.0",
                    "content-length": "227",
                    "origin": "https://mubu.com",
                    "referer": "https://mubu.com/app",
                    "te": "trailers",
                }
            )
            .with_json(
                {
                    "engineType": "MUBU",
                    "messageType": "UNWATCH",
                    "reqId": 18,
                    "requestId": "MESSAGE:5634123:2654354234878869:18",
                    "token": "40gQGtFLg5r",
                    "data": {},
                    "context": {
                        "os": "Windows",
                        "osVersion": "NT 10.0",
                        "appVersion": "default",
                        "platform": "web",
                    },
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
        ),
    ]


if __name__ == "__main__":
    TestCaseMubu().test_start()
